### PR TITLE
For dylan/mtdpart

### PR DESCRIPTION
**Pull request by pabigot**
I recommend this alternative solution, for a couple reasons.

First, since CONFIG_CMD_MTDPARTS was enabled the JFFS partition size defines are never referenced: the entire chunk of cmd_jffs2.c where they would apply is excluded in favor of the version from cmd_mtdparts.c.

Second, the whole point of enabling mtdparts was to support arbitrary MTD partitioning: the original with 4 MB Linux partition, the new default with 8 MB Linux partition, and in the future perhaps adding a new partition for SPL export supporting Falcon Mode booting.  Hard-coding offsets and sizes is fragile.

With mtdparts support in u-boot the correct way to locate the MTD partition holding the linux kernel is to use the partition name, which is linux.  It is necessary to ensure that the mtdparts description is correct for the particular board being booted, which is done by setting the corresponding environment variable.  For example, a board with a pre-dylan installation in NAND that has a 4MB Linux partition can be supported by doing:

```
setenv mtdparts "mtdparts=omap2-nand.0:512k(xloader),1792k(u-boot),256k(environ),4m(linux),-(rootfs)"
```

For jffs2, the fsinfo/fsload commands apply to the current MTD partition, which can be specified through the partition environment variable:

```
setenv partition rootfs
```

Using partition names instead of absolute offsets and sizes makes the system more robust.  (I've verified that fsinfo does read the correct partition in this case, but since I have no Overo COMs with a JFFS2 partition in NAND I was unable to fully verify the solution.)

Wherever this stuff gets documented should include a warning that anybody who ever executed "saveenv" will not see the new boot settings, e.g. the corrected value of nandboot.  In that situation the boot will fail.

(I re-ordered your two commits so with this change the u-boot PR serendipitously matches the number of patches.  These commits are also in my u-boot repository on github in branch gumstix/v2013.07 if you want to pull them.)

### CODE REVIEW

**Comment by ashcharles** [comment]
I need to test this with JFFS2 first.
Can you explain the importance of reordering the patches and having the PR match the number of patches?

**Comment by pabigot** [comment]
I'm curious how your original patch could have affected JFFS2, since as best I could tell the CONFIG_JFFS2 constants you changed weren't referenced with the current command configuration.

Functionally the patches were reordered because I applied them to the u-boot repository before converting the code to use partition labels, and couldn't really justify leaving your original version in when it was essentially reverted by mine: so I rebased to reorder and squash the two mtd ones together.  I very much prefer to be able to generate the patches by format-patch from v2013.07 as we've discussed before, so to me having them in the repository is important.  Personally I'd prefer if we merged from each other's u-boot repository, instead of you using git am to apply the patch to the gumstix u-boot repository, because when you do that the SHA changes which introduces a gratuitous difference in regenerated patches.

That re-ordering allowed the PR to match the patch count again is a foolish consistency that is not necessary, but it appeals to my sense of order so did swing the balance in favor of the approach I picked.

**Comment by ashcharles** [comment]
My 'fixes' for JFFS2 didn't come about because something was strictly broken.  I noticed the memory locations were incorrect based on an 8MB kernel and adjusted.  Realistically though, I didn't understand mtdparts well enough.

**Comment by ashcharles** [comment]
@pabigot Happy to pull from your u-boot repo for the future so we can both have a clean format-patch.  gumstix/u-boot is now technically out of sync but the changes are the same...

**Comment by pabigot** [comment]
Actually, I had rebased my work so that it was a fast-forward from where you had left the gumstix u-boot at the time I made my changes.  It isn't now, though.

**Pull request merged**
